// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw8BajLn5RzysayKtlfKK9eltFGfPMuCc',
    appId: '1:355245928002:web:029ab239f851c95954c7db',
    messagingSenderId: '355245928002',
    projectId: 'task-project-firebase',
    authDomain: 'task-project-firebase.firebaseapp.com',
    storageBucket: 'task-project-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp3BTXNFlX-Jv3n8YoSq_TUWTqrGbtyU',
    appId: '1:355245928002:android:ad338be23a9e804954c7db',
    messagingSenderId: '355245928002',
    projectId: 'task-project-firebase',
    storageBucket: 'task-project-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_e2ad6QApoIkpfOwKFVgHurKe0xzj6rE',
    appId: '1:355245928002:ios:84901c9c0fdca53f54c7db',
    messagingSenderId: '355245928002',
    projectId: 'task-project-firebase',
    storageBucket: 'task-project-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projectManagement',
  );
}
